config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'

  resources :books

  #get "/books/:id", to:"books#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    @books = Book.all
  end

  def show
    @books = Book.find(params[:id])
  end

  def edit
    @books = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    #@books = Book.new
    @books = current_user.books.build
  end

  def create
    #@books = Book.new(book_params)
    @books = current_user.books.build(book_params)
    if @books.save
      redirect_to @books
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other 
  end

  def correct_user
    @book = current_user.books.find_by(id: params[:id])

    redirect_to root_path, notice: "Not Authorized to Edit this Book" if @book.nil?
  end


  private
    def book_params
      params.require(:book).permit(:title, :author, :read, :synopsis, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: books do |form| %>
  <div class='mb-3 px-5'>
    <%= form.text_field :title, class:'form-control', placeholder: "Book Title" %>
  </div>
  <br/>
  <div class='mb-3 px-5'>
    <%= form.text_field :author, class:'form-control', placeholder: "Author Name" %>
  </div>

  <div class='mb-3 px-5'>
    <%= form.label "Have you read this book?" %>
    <%= form.radio_button :read, "true" %>
    <%= form.label "Yes" %>
    <%= form.radio_button :read, "false" %>
    <%= form.label "No" %>
  </div>

  <div class='mb-3 px-5'>
    <%= form.text_area :synopsis, class:'form-control', placeholder: "Write out your quick synopsis here!" %>
  </div>

  <div class='mb-3 px-5'>
    <%= form.number_field :user_id, id: :book_user_id, class:'form-control', value: current_user.id, type: :hidden %>
  </div>

  <div class='text-center'>
    <%= form.submit class:"btn btn-secondary btn-dark"%>
  </div>

<% end %>

app/views/books/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Bookshelf", root_path, class:"navbar-brand"%>
    <%# <a class="navbar-brand" href="#">Bookshelf</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add to Bookshelf", new_book_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link", data: {
              turbo_method: :delete, 
              turbo_confirm: "Are you sure?"
            } %>
          </li>

          <li class="nav-item d-flex">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/books/edit.html.erb
<h1 class='display-4 text-center'>Update your book information</h1>

<%= render 'books/form', books: @books %>
</br>
<div class='text-center'>
  <%= link_to 'Back to main', root_path, class:"btn btn-secondary" %>
</div>

app/views/books/index.html.erb
<h1 class='display-2 text-center'>Welcome to your bookshelf!</h1>

</br>
</br>

<% if !current_user%>
  <h6 class='ps-4 display-5 text-center'>Log in or Sign up to create your bookshelf!</h6>
<% else %>

  <h6 class='ps-4'>Here are your list of books on your bookshelf:</h6>

  <br/>
  <br/>
  <div class='text-center px-5'>
    <% if @books %>
      <table class='table table-striped table-bordered table-responsive table-hover'>
        <thead>
          <th>Title</th>
          <th>Author</th>
          <th>Have I read it?</th>
          <th>Synopsis</th>
        </thead>
      
        <tbody class="table-group-divider">
          <% @books.each do |book| %>
          <% if book.user == current_user %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.author %></td>
              <td>
                <%if book.read %>
                  <%= 'Yes' %>
                <%else%>
                  <%= "No" %>
                <%end%>
              </td>
              <td><%= link_to 'Learn More', book_path(book.id) %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
  <% end %>
  </div>

  <br/>
  <br/>
  <br/>
  <div class='text-center'><%= link_to "Add to shelf", new_book_path, class:"btn btn-dark btn-lg" %></div>
<% end %>

app/views/books/new.html.erb
<h1 class='text-center display-5'><strong>New book on the shelf?</strong></h1>

<%= render 'books/form', books: @books %>
</br>
<div class='text-center'>
  <%= link_to "Back to main", root_path, class:"btn btn-secondary "%>
</div>

app/views/books/show.html.erb
<h1 class='display-4 text-center'><strong><%= @books.title %></strong></h1>
<p class='ps-4'><strong>Synopsis:</strong></p>

<p class='ps-5 lead'>
  <%= @books.synopsis %>
</p>

<div class='text-center'>
  <%= link_to "Edit Info", edit_book_path(@books), class:"btn btn-secondary btn-dark" %> 
  <%= link_to "Delete entry", book_path(@books), class:"btn btn-secondary btn-dark", data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
  </br>
  </br>
  <%= link_to "Back to home", root_path, class:"btn btn-secondary" %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rails Bookshelf</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body style='background-color:#FEFEFE'>


    <%= render 'books/navbar' %>

    <%# authenticaion control flow goes here! %>
    <%# OR NAV BAR %>
    <%# if user_signed_in? %>
      <%# `Hello #{current_user}`%>
      <%#<p class='text-end pe-2'>Sign Out</p> %>
    <%# else %>
      <%#<p class='text-end pe-2'>Log In</p> %>
      <%#<p class='text-end pe-2'>Sign up!</p> %>
    <%# end %>

    <%# for notices with devise %>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>